//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class BOOK_ROOM
    {
        public int BR_ID { get; set; }
        public string br_topic { get; set; }
        public Nullable<System.DateTime> br_date { get; set; }
        public string br_start_time { get; set; }
        public string br_stop_time { get; set; }
        public Nullable<int> MRM_ID { get; set; }
        public Nullable<int> br_person_total { get; set; }
        public string br_remark { get; set; }
        public string br_appr_remark { get; set; }
        public Nullable<int> br_status { get; set; }
        public Nullable<int> br_create_by { get; set; }
        public Nullable<System.DateTime> br_create_date { get; set; }
        public Nullable<int> br_update_by { get; set; }
        public Nullable<System.DateTime> br_update_date { get; set; }
        public Nullable<int> br_appr1_status { get; set; }
        public Nullable<int> br_appr1_by { get; set; }
        public string br_appr1_remark { get; set; }
        public Nullable<System.DateTime> br_appr1_date { get; set; }
        public Nullable<int> br_appr2_status { get; set; }
        public Nullable<int> br_appr2_by { get; set; }
        public string br_appr2_remark { get; set; }
        public Nullable<System.DateTime> br_appr2_date { get; set; }
        public Nullable<int> br_request_by { get; set; }
    }
}
