//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNF_ROOM_STATUS
    {
        public int CRS_ID { get; set; }
        public Nullable<double> CRS_TIME_LIMIT { get; set; }
        public string CRS_DETAIL { get; set; }
        public Nullable<double> CRS_SCORE { get; set; }
        public Nullable<byte> CRS_STATUS { get; set; }
        public Nullable<int> CRS_CREATE_BY { get; set; }
        public Nullable<System.DateTime> CRS_CREATE_DATE { get; set; }
        public Nullable<int> CRS_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> CRS_UPDATE_DATE { get; set; }
    }
}
