//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMP_PROFILE
    {
        public int EMP_ID { get; set; }
        public string emp_code { get; set; }
        public string emp_title { get; set; }
        public string emp_fname { get; set; }
        public string emp_lname { get; set; }
        public string emp_depart_1 { get; set; }
        public string emp_depart_2 { get; set; }
        public string emp_level { get; set; }
        public string emp_shift { get; set; }
        public Nullable<System.DateTime> emp_start_work { get; set; }
        public string emp_age_work { get; set; }
        public string emp_book_permit { get; set; }
        public Nullable<System.DateTime> emp_book_permit_expire { get; set; }
        public string emp_boss { get; set; }
        public string emp_boss_tel { get; set; }
        public Nullable<double> emp_sc_credit { get; set; }
        public string emp_level_work { get; set; }
        public string emp_fund { get; set; }
        public string emp_social_security { get; set; }
        public string emp_cooperative { get; set; }
        public string emp_card_id { get; set; }
        public Nullable<System.DateTime> emp_cardid_expire { get; set; }
        public Nullable<System.DateTime> emp_birthday { get; set; }
        public string emp_sex { get; set; }
        public string emp_age { get; set; }
        public string emp_blood_type { get; set; }
        public string emp_religion { get; set; }
        public string emp_salary_account { get; set; }
        public string emp_tel { get; set; }
        public string emp_email { get; set; }
        public string emp_lineid { get; set; }
        public string emp_current_address { get; set; }
        public string emp_address { get; set; }
        public Nullable<byte> emp_status { get; set; }
        public string emp_card_no { get; set; }
        public Nullable<byte> emp_update_device { get; set; }
        public Nullable<int> emp_group { get; set; }
        public string emp_user_name { get; set; }
        public string emp_password { get; set; }
        public string emp_image { get; set; }
        public Nullable<int> emp_boss_id { get; set; }
        public Nullable<byte> emp_pass_isdefault { get; set; }
    }
}
