//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class IMAGE_SLIDE
    {
        public int IS_ID { get; set; }
        public string is_url_image { get; set; }
        public string is_url_link { get; set; }
        public Nullable<byte> is_status { get; set; }
        public Nullable<short> is_order_by { get; set; }
        public Nullable<System.DateTime> is_update_date { get; set; }
        public Nullable<int> is_update_by { get; set; }
    }
}
