//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_ROOM
    {
        public int MRM_ID { get; set; }
        public string MRM_CODE { get; set; }
        public string MRM_NAME { get; set; }
        public Nullable<byte> MRM_STATUS { get; set; }
        public Nullable<System.DateTime> MRM_CREATE_DATE { get; set; }
        public Nullable<int> MRM_CREATE_BY { get; set; }
        public Nullable<System.DateTime> MRM_UPDATE_DATE { get; set; }
        public Nullable<int> MRM_UPDATE_BY { get; set; }
        public string MRM_COLOR { get; set; }
    }
}
