//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_CAR_TYPE
    {
        public int MCT_ID { get; set; }
        public string MCT_NAME { get; set; }
        public string MCT_DETAIL { get; set; }
        public Nullable<byte> MCT_STATUS { get; set; }
        public Nullable<int> MCT_CREATE_BY { get; set; }
        public Nullable<System.DateTime> MCT_CREATE_DATE { get; set; }
        public Nullable<int> MCT_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> MCT_UPDATE_DATE { get; set; }
    }
}
