//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_DEPARTMENT
    {
        public int MD_ID { get; set; }
        public string md_code { get; set; }
        public string md_name { get; set; }
        public string md_tel { get; set; }
        public Nullable<bool> md_dis_mobile { get; set; }
        public Nullable<byte> md_status { get; set; }
        public Nullable<System.DateTime> md_update_date { get; set; }
    }
}
