//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_PROJECT
    {
        public int MPJ_ID { get; set; }
        public Nullable<short> MPJ_YEAR { get; set; }
        public string MPJ_NAME { get; set; }
        public Nullable<System.DateTime> MPJ_START_DATE { get; set; }
        public Nullable<System.DateTime> MPJ_STOP_DATE { get; set; }
        public string MPJ_DETAIL { get; set; }
        public Nullable<byte> MPJ_STATUS { get; set; }
        public Nullable<System.DateTime> MPJ_CREATE_DATE { get; set; }
        public string MPJ_CREATE_BY { get; set; }
        public Nullable<System.DateTime> MPJ_UPDATE_DATE { get; set; }
        public string MPJ_UPDATE_BY { get; set; }
    }
}
