//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_COURSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAS_COURSE()
        {
            this.TRAINING_ITEM = new HashSet<TRAINING_ITEM>();
        }
    
        public int MCS_ID { get; set; }
        public Nullable<int> MPJ_ID { get; set; }
        public string MCS_NAME { get; set; }
        public string MCS_TYPE { get; set; }
        public Nullable<int> MTD_ID { get; set; }
        public Nullable<int> MEP_ID { get; set; }
        public Nullable<int> MFL_ID { get; set; }
        public string MCS_FILENAME { get; set; }
        public string MCS_REMARK { get; set; }
        public Nullable<double> MCS_FULL_SCORE1 { get; set; }
        public Nullable<double> MCS_FULL_SCORE2 { get; set; }
        public Nullable<double> MCS_FULL_SCORE3 { get; set; }
        public Nullable<double> MCS_FULL_SCORE4 { get; set; }
        public Nullable<double> MCS_FULL_SCORE5 { get; set; }
        public Nullable<System.DateTime> CREATE_DATE { get; set; }
        public string CREATE_BY { get; set; }
        public Nullable<System.DateTime> UPDATE_DATE { get; set; }
        public string UPDATE_BY { get; set; }
        public Nullable<int> MCS_STATUS { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAINING_ITEM> TRAINING_ITEM { get; set; }
    }
}
