//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_FORMULA
    {
        public int MFL_ID { get; set; }
        public string MFL_TYPE { get; set; }
        public string MFL_NAME { get; set; }
        public Nullable<int> MFL_INPUT_TYPE { get; set; }
        public Nullable<byte> MFL_STATUS { get; set; }
        public Nullable<System.DateTime> MFL_CREATE_DATE { get; set; }
        public Nullable<int> MFL_CREATE_BY { get; set; }
        public Nullable<System.DateTime> MFL_UPDATE_DATE { get; set; }
        public Nullable<int> MFL_UPDATE_BY { get; set; }
    }
}
