//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_EXPERT
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAS_EXPERT()
        {
            this.TRAINING_EXPERT = new HashSet<TRAINING_EXPERT>();
        }
    
        public int MEP_ID { get; set; }
        public string MEP_NAME { get; set; }
        public string MEP_TEL { get; set; }
        public Nullable<byte> MEP_STATUS { get; set; }
        public Nullable<int> MEP_CREATE_BY { get; set; }
        public Nullable<System.DateTime> MEP_CREATE_DATE { get; set; }
        public int MEP_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> MEP_UPDATE_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAINING_EXPERT> TRAINING_EXPERT { get; set; }
    }
}
