//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_EXPENSE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MAS_EXPENSE()
        {
            this.TRAINING_EXPENSE = new HashSet<TRAINING_EXPENSE>();
        }
    
        public int MEXP_ID { get; set; }
        public string MEXP_CODE { get; set; }
        public string MEXP_NAME { get; set; }
        public Nullable<byte> MEXP_STATUS { get; set; }
        public Nullable<int> MEXP_CREATE_BY { get; set; }
        public Nullable<System.DateTime> MEXP_CREATE_DATE { get; set; }
        public Nullable<int> MEXP_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> MEXP_UPDATE_DATE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAINING_EXPENSE> TRAINING_EXPENSE { get; set; }
    }
}
