//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_CAR
    {
        public int MCA_ID { get; set; }
        public Nullable<int> MCT_ID { get; set; }
        public string MCA_NAME { get; set; }
        public string MCA_DETAIL { get; set; }
        public Nullable<byte> MCA_STATUS { get; set; }
        public Nullable<int> MCA_CREATE_BY { get; set; }
        public Nullable<System.DateTime> MCA_CREATE_DATE { get; set; }
        public Nullable<int> MCA_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> MCA_UPDATE_DATE { get; set; }
        public string MCA_COLOR { get; set; }
    }
}
