//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_HARDWARE
    {
        public int MHW_ID { get; set; }
        public string MHW_NAME { get; set; }
        public byte MHW_STATUS { get; set; }
        public System.DateTime MHW_CREATE_DATE { get; set; }
        public int MHW_CREATE_BY { get; set; }
        public System.DateTime MHW_UPDATE_DATE { get; set; }
        public int MHW_UPDATE_BY { get; set; }
    }
}
