//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_PROGRAM
    {
        public int Program_ID { get; set; }
        public string Program_Group_Id { get; set; }
        public string Program_Group_Name { get; set; }
        public string Program_Name { get; set; }
        public string Url_Path { get; set; }
        public bool Active { get; set; }
        public Nullable<int> Order_Item { get; set; }
    }
}
