//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class MAS_CAR_REASON
    {
        public int MCR_ID { get; set; }
        public string MCR_NAME { get; set; }
        public string MCR_DETAIL { get; set; }
        public Nullable<byte> MCR_STATUS { get; set; }
        public string MCR_CREATE_BY { get; set; }
        public Nullable<System.DateTime> MCR_CREATE_DATE { get; set; }
        public string MCR_UPDATE_BY { get; set; }
        public Nullable<System.DateTime> MCR_UPDATE_DATE { get; set; }
    }
}
