//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class NEWS
    {
        public int NW_ID { get; set; }
        public Nullable<int> nw_type { get; set; }
        public string nw_topic { get; set; }
        public string nw_detail { get; set; }
        public string nw_image { get; set; }
        public string nw_vdo { get; set; }
        public Nullable<System.DateTime> nw_date { get; set; }
        public Nullable<byte> nw_status { get; set; }
        public Nullable<System.DateTime> nw_update_date { get; set; }
        public Nullable<int> nw_update_by { get; set; }
    }
}
