//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIME_ATT_IMAGE
    {
        public int TARI_ID { get; set; }
        public Nullable<int> TAR_ID { get; set; }
        public string tari_image { get; set; }
        public Nullable<System.DateTime> tari_update_date { get; set; }
    }
}
