//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIME_ATT_REALTIME
    {
        public int TAR_ID { get; set; }
        public Nullable<System.DateTime> tar_date { get; set; }
        public Nullable<System.DateTime> tar_time { get; set; }
        public string tar_ip { get; set; }
        public string card_no { get; set; }
        public Nullable<byte> tar_type { get; set; }
        public Nullable<int> MN_ID { get; set; }
        public string emp_code { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string m_lat { get; set; }
        public string m_long { get; set; }
        public Nullable<short> tar_status { get; set; }
        public Nullable<short> send_status { get; set; }
        public string Remark { get; set; }
    }
}
