//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_EMP
    {
        public int TrainingEmpId { get; set; }
        public string TrainingEmpCode { get; set; }
        public int TrainingId { get; set; }
        public int TrainingItemId { get; set; }
        public string TrainingEmpScore1 { get; set; }
        public string TrainingEmpScore2 { get; set; }
        public string TrainingEmpScore3 { get; set; }
        public string TrainingEmpScore4 { get; set; }
        public string TrainingEmpScore5 { get; set; }
        public string TrainingEmpScoreTotal { get; set; }
        public string TrainingEmpResult { get; set; }
        public Nullable<System.DateTime> CheckinDate { get; set; }
        public Nullable<int> CheckinStatus { get; set; }
        public string CheckinRemark { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
    
        public virtual TRAINING_ITEM TRAINING_ITEM { get; set; }
        public virtual TRAINING TRAINING { get; set; }
    }
}
