//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TRAINING()
        {
            this.TRAINING_EMP = new HashSet<TRAINING_EMP>();
            this.TRAINING_EXPENSE = new HashSet<TRAINING_EXPENSE>();
            this.TRAINING_EXPERT = new HashSet<TRAINING_EXPERT>();
        }
    
        public int TrainingId { get; set; }
        public string TrainingName { get; set; }
        public Nullable<System.DateTime> TrainingDateFrom { get; set; }
        public Nullable<System.DateTime> TrainingDateTo { get; set; }
        public Nullable<byte> TrainingStatus { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<int> CreateBy { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> UpdateBy { get; set; }
        public string TrainingNo { get; set; }
        public Nullable<System.DateTime> TrainingDate { get; set; }
        public string TrainingTime { get; set; }
        public Nullable<int> MCS_ID { get; set; }
        public Nullable<int> MRM_ID { get; set; }
        public string TrainingTimeStart { get; set; }
        public string TrainingTimeStop { get; set; }
        public Nullable<int> MFL_ID { get; set; }
        public string filename { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAINING_EMP> TRAINING_EMP { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAINING_EXPENSE> TRAINING_EXPENSE { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TRAINING_EXPERT> TRAINING_EXPERT { get; set; }
    }
}
