//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRAINING_EXPERT
    {
        public int TrainingExpertId { get; set; }
        public int TrainingId { get; set; }
        public int TrainingItemId { get; set; }
        public int ExpertId { get; set; }
    
        public virtual MAS_EXPERT MAS_EXPERT { get; set; }
        public virtual TRAINING_ITEM TRAINING_ITEM { get; set; }
        public virtual TRAINING TRAINING { get; set; }
    }
}
