//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StandardCan
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER_ROLE
    {
        public int Role_ID { get; set; }
        public string Group_ID { get; set; }
        public string Program_ID { get; set; }
        public bool Active { get; set; }
        public System.DateTime Create_Date { get; set; }
        public int Create_By { get; set; }
        public System.DateTime Update_Date { get; set; }
        public int Update_By { get; set; }
    }
}
