// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("BOOK_TIME_STATUS")]
    public partial class BookTimeStatus
    {
        [Key]
        [Column("BTS_ID")]
        public int BtsId { get; set; }
        [Column("bts_name")]
        [StringLength(50)]
        public string BtsName { get; set; }
    }
}