// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("BOOK_CAR_EMP")]
    public partial class BookCarEmp
    {
        [Key]
        [Column("BC_ID")]
        public int BcId { get; set; }
        [Key]
        [Column("emp_code")]
        [StringLength(20)]
        public string EmpCode { get; set; }
        [Column("checkin_date", TypeName = "datetime")]
        public DateTime? CheckinDate { get; set; }
        [Column("checkin_status")]
        public int? CheckinStatus { get; set; }
        [Column("checkin_remark", TypeName = "text")]
        public string CheckinRemark { get; set; }
        [Column("update_date", TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
    }
}