// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("BOOK_CAR")]
    public partial class BookCar
    {
        [Key]
        [Column("BC_ID")]
        public int BcId { get; set; }
        [Column("bc_topic", TypeName = "text")]
        public string BcTopic { get; set; }
        [Column("bc_start_date", TypeName = "date")]
        public DateTime? BcStartDate { get; set; }
        [Column("bc_start_time")]
        [StringLength(5)]
        public string BcStartTime { get; set; }
        [Column("bc_stop_date", TypeName = "date")]
        public DateTime? BcStopDate { get; set; }
        [Column("bc_stop_time")]
        [StringLength(5)]
        public string BcStopTime { get; set; }
        [Column("bc_person_total")]
        public int? BcPersonTotal { get; set; }
        [Column("MCT_ID")]
        public int? MctId { get; set; }
        [Column("MCA_ID")]
        public int? McaId { get; set; }
        [Column("MCR_ID")]
        public int? McrId { get; set; }
        [Column("MDT_ID")]
        public int? MdtId { get; set; }
        [Column("bc_remark", TypeName = "text")]
        public string BcRemark { get; set; }
        [Column("bc_appr_remark", TypeName = "text")]
        public string BcApprRemark { get; set; }
        [Column("bc_status")]
        public int? BcStatus { get; set; }
        [Column("bc_create_by")]
        [StringLength(20)]
        public string BcCreateBy { get; set; }
        [Column("bc_create_date", TypeName = "datetime")]
        public DateTime? BcCreateDate { get; set; }
        [Column("bc_update_by")]
        [StringLength(20)]
        public string BcUpdateBy { get; set; }
        [Column("bc_update_date", TypeName = "datetime")]
        public DateTime? BcUpdateDate { get; set; }
        [Column("bc_appr_status")]
        public int? BcApprStatus { get; set; }
        [Column("bc_appr_by")]
        [StringLength(20)]
        public string BcApprBy { get; set; }
        [Column("bc_appr_date", TypeName = "datetime")]
        public DateTime? BcApprDate { get; set; }
    }
}