// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("BOOK_ROOM_DEVICE")]
    public partial class BookRoomDevice
    {
        [Key]
        [Column("BR_ID")]
        public int BrId { get; set; }
        [Key]
        [Column("MHW_ID")]
        public int MhwId { get; set; }
    }
}