// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("CNF_REPORT")]
    public partial class CnfReport
    {
        [Key]
        [Column("CPR_ID")]
        public int CprId { get; set; }
        [Column("CPR_REPORT")]
        [StringLength(50)]
        public string CprReport { get; set; }
        [Column("CPR_NAME")]
        [StringLength(50)]
        public string CprName { get; set; }
        [Column("CPR_CREATE_BY")]
        public int? CprCreateBy { get; set; }
        [Column("CPR_CREATE_DATE", TypeName = "datetime")]
        public DateTime? CprCreateDate { get; set; }
        [Column("CPR_UPDATE_BY")]
        public int? CprUpdateBy { get; set; }
        [Column("CPR_UPDATE_DATE", TypeName = "datetime")]
        public DateTime? CprUpdateDate { get; set; }
    }
}