// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("CNF_ROOM_STATUS")]
    public partial class CnfRoomStatus
    {
        [Key]
        [Column("CRS_ID")]
        public int CrsId { get; set; }
        [Column("CRS_TIME_LIMIT")]
        public double? CrsTimeLimit { get; set; }
        [Column("CRS_DETAIL")]
        [StringLength(50)]
        public string CrsDetail { get; set; }
        [Column("CRS_SCORE")]
        public double? CrsScore { get; set; }
        [Column("CRS_STATUS")]
        public byte? CrsStatus { get; set; }
        [Column("CRS_CREATE_BY")]
        public int? CrsCreateBy { get; set; }
        [Column("CRS_CREATE_DATE", TypeName = "datetime")]
        public DateTime? CrsCreateDate { get; set; }
        [Column("CRS_UPDATE_BY")]
        public int? CrsUpdateBy { get; set; }
        [Column("CRS_UPDATE_DATE", TypeName = "datetime")]
        public DateTime? CrsUpdateDate { get; set; }
    }
}