// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("EMP_BEHAVIOR")]
    public partial class EmpBehavior
    {
        [Key]
        [Column("EB_ID")]
        public int EbId { get; set; }
        [Column("emp_code")]
        [StringLength(20)]
        public string EmpCode { get; set; }
        [Column("eb_year")]
        public int? EbYear { get; set; }
        [Column("eb_date", TypeName = "date")]
        public DateTime? EbDate { get; set; }
        [Column("eb_detail", TypeName = "text")]
        public string EbDetail { get; set; }
        [Column("eb_score")]
        public double? EbScore { get; set; }
        [Column("eb_status")]
        public byte? EbStatus { get; set; }
        [Column("eb_create_date", TypeName = "datetime")]
        public DateTime? EbCreateDate { get; set; }
        [Column("eb_create_by")]
        [StringLength(20)]
        public string EbCreateBy { get; set; }
        [Column("eb_update_date", TypeName = "datetime")]
        public DateTime? EbUpdateDate { get; set; }
        [Column("eb_update_by")]
        [StringLength(20)]
        public string EbUpdateBy { get; set; }
    }
}