// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("EMP_CARD")]
    public partial class EmpCard
    {
        [Key]
        [Column("EC_ID")]
        public int EcId { get; set; }
        [Column("emp_code")]
        [StringLength(20)]
        public string EmpCode { get; set; }
        [Column("ec_date", TypeName = "date")]
        public DateTime? EcDate { get; set; }
        [Column("ec_card_no")]
        [StringLength(12)]
        public string EcCardNo { get; set; }
        [Column("ec_status")]
        public byte? EcStatus { get; set; }
        [Column("ec_create_date", TypeName = "datetime")]
        public DateTime? EcCreateDate { get; set; }
        [Column("ec_create_by")]
        [StringLength(20)]
        public string EcCreateBy { get; set; }
        [Column("ec_update_date", TypeName = "datetime")]
        public DateTime? EcUpdateDate { get; set; }
        [Column("ec_update_by")]
        [StringLength(20)]
        public string EcUpdateBy { get; set; }
    }
}