// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("EMP_LEAVE_SUMMARY")]
    public partial class EmpLeaveSummary
    {
        [Key]
        [Column("ESL_ID")]
        public int EslId { get; set; }
        [Column("emp_code")]
        [StringLength(20)]
        public string EmpCode { get; set; }
        [Column("esl_start_date", TypeName = "date")]
        public DateTime? EslStartDate { get; set; }
        [Column("esl_stop_date", TypeName = "date")]
        public DateTime? EslStopDate { get; set; }
        [Column("esl_total_day")]
        public byte? EslTotalDay { get; set; }
        [Column("esl_type")]
        [StringLength(50)]
        public string EslType { get; set; }
        [Column("esl_remark")]
        [StringLength(200)]
        public string EslRemark { get; set; }
        /// <summary>
        /// วันที่ทำรายการ
        /// </summary>
        [Column("esl_status")]
        [StringLength(50)]
        public string EslStatus { get; set; }
        [Column("esl_update_date", TypeName = "datetime")]
        public DateTime? EslUpdateDate { get; set; }
    }
}