// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("EMP_LEAVE_QUOTA")]
    public partial class EmpLeaveQuota
    {
        [Key]
        [Column("ELQ_ID")]
        public int ElqId { get; set; }
        [Column("emp_code")]
        [StringLength(20)]
        public string EmpCode { get; set; }
        [Column("esq_year")]
        public int? EsqYear { get; set; }
        [Column("esq_type_code")]
        [StringLength(20)]
        public string EsqTypeCode { get; set; }
        [Column("esq_cumulative_total")]
        public int? EsqCumulativeTotal { get; set; }
        [Column("esq_present_total")]
        public int? EsqPresentTotal { get; set; }
        [Column("esq_use_total")]
        public int? EsqUseTotal { get; set; }
        [Column("esq_net_total")]
        public int? EsqNetTotal { get; set; }
        [Column("esq_update_date", TypeName = "datetime")]
        public DateTime? EsqUpdateDate { get; set; }
    }
}