// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("EMP_NOTE")]
    public partial class EmpNote
    {
        [Key]
        [Column("emp_code")]
        [StringLength(20)]
        public string EmpCode { get; set; }
        [Column("emp_note", TypeName = "text")]
        public string EmpNote1 { get; set; }
        [Column("create_date", TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [Column("create_by")]
        [StringLength(20)]
        public string CreateBy { get; set; }
        [Column("update_date", TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
        [Column("update_by")]
        [StringLength(20)]
        public string UpdateBy { get; set; }
    }
}