// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("EMP_PROFILE")]
    public partial class EmpProfile
    {
        [Key]
        [Column("EMP_ID")]
        public int EmpId { get; set; }
        [Column("emp_code")]
        [StringLength(20)]
        public string EmpCode { get; set; }
        [Column("emp_title")]
        [StringLength(50)]
        public string EmpTitle { get; set; }
        [Column("emp_fname")]
        [StringLength(100)]
        public string EmpFname { get; set; }
        [Column("emp_lname")]
        [StringLength(100)]
        public string EmpLname { get; set; }
        /// <summary>
        /// &#3613;&#3656;&#3634;&#3618;
        /// </summary>
        [Column("emp_depart_1")]
        [StringLength(100)]
        public string EmpDepart1 { get; set; }
        /// <summary>
        /// &#3649;&#3612;&#3609;&#3585;
        /// </summary>
        [Column("emp_depart_2")]
        [StringLength(100)]
        public string EmpDepart2 { get; set; }
        [Column("emp_level")]
        [StringLength(50)]
        public string EmpLevel { get; set; }
        [Column("emp_shift")]
        [StringLength(50)]
        public string EmpShift { get; set; }
        /// <summary>
        /// &#3623;&#3633;&#3609;&#3607;&#3637;&#3656;&#3648;&#3619;&#3636;&#3656;&#3617;&#3591;&#3634;&#3609;
        /// </summary>
        [Column("emp_start_work", TypeName = "date")]
        public DateTime? EmpStartWork { get; set; }
        [Column("emp_age_work")]
        [StringLength(30)]
        public string EmpAgeWork { get; set; }
        [Column("emp_book_permit")]
        [StringLength(30)]
        public string EmpBookPermit { get; set; }
        [Column("emp_book_permit_expire", TypeName = "date")]
        public DateTime? EmpBookPermitExpire { get; set; }
        [Column("emp_boss_id")]
        public int? EmpBossId { get; set; }
        [Column("emp_boss")]
        [StringLength(100)]
        public string EmpBoss { get; set; }
        [Column("emp_boss_tel")]
        [StringLength(100)]
        public string EmpBossTel { get; set; }
        [Column("emp_sc_credit")]
        public double? EmpScCredit { get; set; }
        /// <summary>
        /// &#3619;&#3632;&#3604;&#3633;&#3610;&#3612;&#3621;&#3591;&#3634;&#3609;
        /// </summary>
        [Column("emp_level_work")]
        [StringLength(10)]
        public string EmpLevelWork { get; set; }
        /// <summary>
        /// &#3585;&#3629;&#3591;&#3607;&#3640;&#3609;&#3626;&#3635;&#3619;&#3629;&#3591;
        /// </summary>
        [Column("emp_fund")]
        [StringLength(50)]
        public string EmpFund { get; set; }
        /// <summary>
        /// &#3611;&#3619;&#3632;&#3585;&#3633;&#3609;&#3626;&#3633;&#3591;&#3588;&#3617;
        /// </summary>
        [Column("emp_social_security")]
        [StringLength(50)]
        public string EmpSocialSecurity { get; set; }
        /// <summary>
        /// &#3626;&#3627;&#3585;&#3619;&#3603;&#3660;
        /// </summary>
        [Column("emp_cooperative")]
        [StringLength(50)]
        public string EmpCooperative { get; set; }
        [Column("emp_card_id")]
        [StringLength(20)]
        public string EmpCardId { get; set; }
        [Column("emp_cardid_expire", TypeName = "date")]
        public DateTime? EmpCardidExpire { get; set; }
        [Column("emp_birthday", TypeName = "date")]
        public DateTime? EmpBirthday { get; set; }
        [Column("emp_sex")]
        [StringLength(10)]
        public string EmpSex { get; set; }
        [Column("emp_age")]
        [StringLength(3)]
        public string EmpAge { get; set; }
        [Column("emp_blood_type")]
        [StringLength(10)]
        public string EmpBloodType { get; set; }
        [Column("emp_religion")]
        [StringLength(20)]
        public string EmpReligion { get; set; }
        [Column("emp_salary_account")]
        [StringLength(20)]
        public string EmpSalaryAccount { get; set; }
        [Column("emp_tel")]
        [StringLength(50)]
        public string EmpTel { get; set; }
        [Column("emp_email")]
        [StringLength(30)]
        public string EmpEmail { get; set; }
        [Column("emp_lineid")]
        [StringLength(30)]
        public string EmpLineid { get; set; }
        [Column("emp_current_address", TypeName = "text")]
        public string EmpCurrentAddress { get; set; }
        [Column("emp_address", TypeName = "text")]
        public string EmpAddress { get; set; }
        /// <summary>
        /// 0: &#3629;&#3629;&#3585;&#3592;&#3634;&#3585;&#3591;&#3634;&#3609;, 1: &#3611;&#3585;&#3605;&#3636;
        /// </summary>
        [Column("emp_status")]
        public byte? EmpStatus { get; set; }
        [Column("emp_card_no")]
        [StringLength(15)]
        public string EmpCardNo { get; set; }
        [Column("emp_update_device")]
        public byte? EmpUpdateDevice { get; set; }
        [Column("emp_group")]
        public int? EmpGroup { get; set; }
        [Column("emp_user_name")]
        [StringLength(20)]
        public string EmpUserName { get; set; }
        [Column("emp_password")]
        [StringLength(100)]
        public string EmpPassword { get; set; }
        [Column("emp_image")]
        [StringLength(200)]
        public string EmpImage { get; set; }
        [Column("emp_pass_isdefault")]
        public byte? EmpPassIsdefault { get; set; }
    }
}