// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("EMP_WORKS")]
    public partial class EmpWorks
    {
        [Key]
        [Column("EW_ID")]
        public int EwId { get; set; }
        [Column("emp_code")]
        [StringLength(20)]
        public string EmpCode { get; set; }
        [Column("ew_no")]
        public byte? EwNo { get; set; }
        [Column("ew_date", TypeName = "date")]
        public DateTime? EwDate { get; set; }
        [Column("ew_grade")]
        [StringLength(5)]
        public string EwGrade { get; set; }
        [Column("ew_status")]
        public byte? EwStatus { get; set; }
        [Column("ew_create_date", TypeName = "datetime")]
        public DateTime? EwCreateDate { get; set; }
        [Column("ew_create_by")]
        [StringLength(20)]
        public string EwCreateBy { get; set; }
        [Column("ew_update_date", TypeName = "datetime")]
        public DateTime? EwUpdateDate { get; set; }
        [Column("ew_update_by")]
        [StringLength(20)]
        public string EwUpdateBy { get; set; }
    }
}