// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("interface_log")]
    public partial class InterfaceLog
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("module")]
        [StringLength(50)]
        public string Module { get; set; }
        [Column("data_log", TypeName = "text")]
        public string DataLog { get; set; }
        [Column("update_date", TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
    }
}