// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("MAS_APPROVE_STATUS")]
    public partial class MasApproveStatus
    {
        [Key]
        [Column("MAS_ID")]
        public int MasId { get; set; }
        [Column("mas_name")]
        [StringLength(50)]
        public string MasName { get; set; }
        [Column("mas_orderby")]
        public short? MasOrderby { get; set; }
        [Column("mas_color")]
        [StringLength(10)]
        public string MasColor { get; set; }
    }
}