// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("MAS_CAR_TYPE")]
    public partial class MasCarType
    {
        [Key]
        [Column("MCT_ID")]
        public int MctId { get; set; }
        [Column("MCT_NAME")]
        [StringLength(50)]
        public string MctName { get; set; }
        [Column("MCT_DETAIL")]
        [StringLength(300)]
        public string MctDetail { get; set; }
        [Column("MCT_STATUS")]
        public byte? MctStatus { get; set; }
        [Column("MCT_CREATE_BY")]
        public int? MctCreateBy { get; set; }
        [Column("MCT_CREATE_DATE", TypeName = "datetime")]
        public DateTime? MctCreateDate { get; set; }
        [Column("MCT_UPDATE_BY")]
        public int? MctUpdateBy { get; set; }
        [Column("MCT_UPDATE_DATE", TypeName = "datetime")]
        public DateTime? MctUpdateDate { get; set; }
    }
}