// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("MAS_COURSE")]
    public partial class MasCourse
    {
        [Key]
        [Column("MCS_ID")]
        public int McsId { get; set; }
        /// <summary>
        /// โครงการ
        /// </summary>
        [Column("MPJ_ID")]
        public int? MpjId { get; set; }
        /// <summary>
        /// ชื่อหลักสูตร
        /// </summary>
        [Column("MCS_NAME")]
        [StringLength(300)]
        public string McsName { get; set; }
        /// <summary>
        /// ประเภทหลักสูตร O,X
        /// </summary>
        [Column("MCS_TYPE")]
        [StringLength(1)]
        public string McsType { get; set; }
        /// <summary>
        /// สถานที่
        /// </summary>
        [Column("MTD_ID")]
        public int? MtdId { get; set; }
        /// <summary>
        /// วิทยากร
        /// </summary>
        [Column("MEP_ID")]
        public int? MepId { get; set; }
        /// <summary>
        /// สูตรคำนวณ
        /// </summary>
        [Column("MFL_ID")]
        public int? MflId { get; set; }
        [Column("MCS_FILENAME")]
        [StringLength(50)]
        public string McsFilename { get; set; }
        [Column("MCS_REMARK")]
        [StringLength(500)]
        public string McsRemark { get; set; }
        [Column("MCS_FULL_SCORE1")]
        public double? McsFullScore1 { get; set; }
        [Column("MCS_FULL_SCORE2")]
        public double? McsFullScore2 { get; set; }
        [Column("MCS_FULL_SCORE3")]
        public double? McsFullScore3 { get; set; }
        [Column("MCS_FULL_SCORE4")]
        public double? McsFullScore4 { get; set; }
        [Column("MCS_FULL_SCORE5")]
        public double? McsFullScore5 { get; set; }
        [Column("CREATE_DATE", TypeName = "datetime")]
        public DateTime? CreateDate { get; set; }
        [Column("CREATE_BY")]
        [StringLength(20)]
        public string CreateBy { get; set; }
        [Column("UPDATE_DATE", TypeName = "datetime")]
        public DateTime? UpdateDate { get; set; }
        [Column("UPDATE_BY")]
        [StringLength(20)]
        public string UpdateBy { get; set; }
    }
}