// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("MAS_DEPARTMENT")]
    public partial class MasDepartment
    {
        [Key]
        [Column("MD_ID")]
        public int MdId { get; set; }
        [Column("md_code")]
        [StringLength(20)]
        public string MdCode { get; set; }
        [Column("md_name")]
        [StringLength(200)]
        public string MdName { get; set; }
        [Column("md_tel")]
        [StringLength(20)]
        public string MdTel { get; set; }
        [Column("md_dis_mobile")]
        public bool? MdDisMobile { get; set; }
        [Column("md_status")]
        public byte? MdStatus { get; set; }
        [Column("md_update_date", TypeName = "datetime")]
        public DateTime? MdUpdateDate { get; set; }
    }
}