// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("MAS_EMPLOYEE_OFFSITE")]
    public partial class MasEmployeeOffsite
    {
        [Key]
        [Column("MOF_ID")]
        public int MofId { get; set; }
        /// <summary>
        /// 1: พนักงานที่เช็คอิน (ประจำ), 2: พนักงานที่เช็คอิน (ชั่วคราว)
        /// </summary>
        [Column("MOF_TYPE")]
        public byte? MofType { get; set; }
        [Column("MOF_EMP_ID")]
        [StringLength(20)]
        public string MofEmpId { get; set; }
        [Column("MOF_START_DATE", TypeName = "date")]
        public DateTime? MofStartDate { get; set; }
        [Column("MOF_STOP_DATE", TypeName = "date")]
        public DateTime? MofStopDate { get; set; }
        [Column("MOF_STATUS")]
        public byte? MofStatus { get; set; }
        [Column("MOF_CREATE_DATE", TypeName = "datetime")]
        public DateTime? MofCreateDate { get; set; }
        [Column("MOF_CREATE_BY")]
        [StringLength(20)]
        public string MofCreateBy { get; set; }
        [Column("MOF_UPDATE_DATE", TypeName = "datetime")]
        public DateTime? MofUpdateDate { get; set; }
        [Column("MOF_UPDATE_BY")]
        [StringLength(20)]
        public string MofUpdateBy { get; set; }
    }
}