// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("MAS_EXPENSE")]
    public partial class MasExpense
    {
        [Key]
        [Column("MEXP_ID")]
        public int MexpId { get; set; }
        [Column("MEXP_CODE")]
        [StringLength(20)]
        public string MexpCode { get; set; }
        [Column("MEXP_NAME")]
        [StringLength(150)]
        public string MexpName { get; set; }
        [Column("MEXP_STATUS")]
        public byte? MexpStatus { get; set; }
        [Column("MEXP_CREATE_BY")]
        public int? MexpCreateBy { get; set; }
        [Column("MEXP_CREATE_DATE", TypeName = "datetime")]
        public DateTime? MexpCreateDate { get; set; }
        [Column("MEXP_UPDATE_BY")]
        public int? MexpUpdateBy { get; set; }
        [Column("MEXP_UPDATE_DATE", TypeName = "datetime")]
        public DateTime? MexpUpdateDate { get; set; }
    }
}