// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("MAS_EXPERT")]
    public partial class MasExpert
    {
        [Key]
        [Column("MEP_ID")]
        public int MepId { get; set; }
        [Column("MEP_NAME")]
        [StringLength(200)]
        public string MepName { get; set; }
        [Column("MEP_TEL")]
        [StringLength(50)]
        public string MepTel { get; set; }
        [Column("MEP_STATUS")]
        public byte? MepStatus { get; set; }
        [Column("MEP_CREATE_BY")]
        public int? MepCreateBy { get; set; }
        [Column("MEP_CREATE_DATE", TypeName = "datetime")]
        public DateTime? MepCreateDate { get; set; }
        [Column("MEP_UPDATE_BY")]
        public int MepUpdateBy { get; set; }
        [Column("MEP_UPDATE_DATE", TypeName = "datetime")]
        public DateTime? MepUpdateDate { get; set; }
    }
}