// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("MAS_FORMULA")]
    public partial class MasFormula
    {
        [Key]
        [Column("MFL_ID")]
        public int MflId { get; set; }
        /// <summary>
        /// O, X
        /// </summary>
        [Column("MFL_TYPE")]
        [StringLength(1)]
        public string MflType { get; set; }
        [Column("MFL_NAME")]
        [StringLength(200)]
        public string MflName { get; set; }
        /// <summary>
        /// 1: ช่องป้อนข้อมูล, 2: ตัวเลือกคะแนน
        /// </summary>
        [Column("MFL_INPUT_TYPE")]
        public int? MflInputType { get; set; }
        [Column("MFL_STATUS")]
        public byte? MflStatus { get; set; }
        [Column("MFL_CREATE_DATE", TypeName = "datetime")]
        public DateTime? MflCreateDate { get; set; }
        [Column("MFL_CREATE_BY")]
        public int? MflCreateBy { get; set; }
        [Column("MFL_UPDATE_DATE", TypeName = "date")]
        public DateTime? MflUpdateDate { get; set; }
        [Column("MFL_UPDATE_BY")]
        public int? MflUpdateBy { get; set; }
    }
}