// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("MAS_FORMULA_VALUE")]
    public partial class MasFormulaValue
    {
        [Key]
        [Column("MFV_ID")]
        public int MfvId { get; set; }
        [Column("MFL_ID")]
        public int? MflId { get; set; }
        [Column("MFV_ORDER_BY")]
        public byte? MfvOrderBy { get; set; }
        [Column("MFV_VALUE")]
        [StringLength(5)]
        public string MfvValue { get; set; }
        [Column("MFV_TEXT")]
        [StringLength(50)]
        public string MfvText { get; set; }
        [Column("MFV_STATUS")]
        public byte? MfvStatus { get; set; }
        [Column("MFV_CREATE_DATE", TypeName = "datetime")]
        public DateTime? MfvCreateDate { get; set; }
        [Column("MFV_CREATE_BY")]
        public int? MfvCreateBy { get; set; }
        [Column("MFV_UPDATE_DATE", TypeName = "datetime")]
        public DateTime? MfvUpdateDate { get; set; }
        [Column("MFV_UPDATE_BY")]
        public int? MfvUpdateBy { get; set; }
    }
}