// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("MAS_FORMULA_RANG")]
    public partial class MasFormulaRang
    {
        [Key]
        [Column("MFR_ID")]
        public int MfrId { get; set; }
        [Column("MFL_ID")]
        public int MflId { get; set; }
        [Column("MFL_NO")]
        public byte MflNo { get; set; }
        [Column("MFL_RANG_SCORE")]
        public double MflRangScore { get; set; }
        [Required]
        [Column("MFL_DISPLAY")]
        [StringLength(50)]
        public string MflDisplay { get; set; }
        [Column("MFL_STATUS")]
        public byte MflStatus { get; set; }
        [Column("MFL_CREATE_DATE", TypeName = "datetime")]
        public DateTime? MflCreateDate { get; set; }
        [Column("MFL_CREATE_BY")]
        public int? MflCreateBy { get; set; }
        [Column("MFL_UPDATE_DATE", TypeName = "datetime")]
        public DateTime? MflUpdateDate { get; set; }
        [Column("MFL_UPDATE_BY")]
        public int? MflUpdateBy { get; set; }
    }
}