// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("MAS_FORMULA_TYPE")]
    public partial class MasFormulaType
    {
        [Key]
        [Column("MFT_ID")]
        [StringLength(2)]
        public string MftId { get; set; }
        [Column("MFT_NAME")]
        [StringLength(100)]
        public string MftName { get; set; }
    }
}