// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("MAS_HOLIDAY")]
    public partial class MasHoliday
    {
        [Key]
        [Column("MHD_ID")]
        public int MhdId { get; set; }
        [Column("MHD_DATE", TypeName = "date")]
        public DateTime? MhdDate { get; set; }
        [Column("MHD_NAME")]
        [StringLength(200)]
        public string MhdName { get; set; }
        [Column("MHD_UPDATE_DATE", TypeName = "datetime")]
        public DateTime? MhdUpdateDate { get; set; }
    }
}