// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("MAS_PROJECT")]
    public partial class MasProject
    {
        [Key]
        [Column("MPJ_ID")]
        public int MpjId { get; set; }
        [Column("MPJ_YEAR")]
        public short? MpjYear { get; set; }
        [Column("MPJ_NAME")]
        [StringLength(200)]
        public string MpjName { get; set; }
        [Column("MPJ_START_DATE", TypeName = "date")]
        public DateTime? MpjStartDate { get; set; }
        [Column("MPJ_STOP_DATE", TypeName = "date")]
        public DateTime? MpjStopDate { get; set; }
        [Column("MPJ_DETAIL")]
        [StringLength(300)]
        public string MpjDetail { get; set; }
        [Column("MPJ_STATUS")]
        public byte? MpjStatus { get; set; }
        [Column("MPJ_CREATE_DATE", TypeName = "date")]
        public DateTime? MpjCreateDate { get; set; }
        [Column("MPJ_CREATE_BY")]
        [StringLength(20)]
        public string MpjCreateBy { get; set; }
        [Column("MPJ_UPDATE_DATE", TypeName = "date")]
        public DateTime? MpjUpdateDate { get; set; }
        [Column("MPJ_UPDATE_BY")]
        [StringLength(20)]
        public string MpjUpdateBy { get; set; }
    }
}