// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("MAS_ROOM")]
    public partial class MasRoom
    {
        [Key]
        [Column("MRM_ID")]
        public int MrmId { get; set; }
        [Column("MRM_CODE")]
        [StringLength(20)]
        public string MrmCode { get; set; }
        [Column("MRM_NAME")]
        [StringLength(300)]
        public string MrmName { get; set; }
        [Column("MRM_STATUS")]
        public byte? MrmStatus { get; set; }
        [Column("MRM_CREATE_DATE", TypeName = "datetime")]
        public DateTime? MrmCreateDate { get; set; }
        [Column("MRM_CREATE_BY")]
        public int? MrmCreateBy { get; set; }
        [Column("MRM_UPDATE_DATE", TypeName = "datetime")]
        public DateTime? MrmUpdateDate { get; set; }
        [Column("MRM_UPDATE_BY")]
        public int? MrmUpdateBy { get; set; }
    }
}