// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("MAS_SECTION_HEAD")]
    public partial class MasSectionHead
    {
        [Key]
        [Column("DS_ID")]
        public int DsId { get; set; }
        [Column("ds_code")]
        [StringLength(20)]
        public string DsCode { get; set; }
        [Column("ds_name")]
        [StringLength(200)]
        public string DsName { get; set; }
        [Column("ds_status")]
        public byte? DsStatus { get; set; }
        [Column("ds_update_date", TypeName = "datetime")]
        public DateTime? DsUpdateDate { get; set; }
    }
}