// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("MAS_TRAIN_DESTINATION")]
    public partial class MasTrainDestination
    {
        [Key]
        [Column("MTD_ID")]
        public int MtdId { get; set; }
        [Column("MTD_NAME")]
        [StringLength(500)]
        public string MtdName { get; set; }
        [Column("MTD_STATUS")]
        public byte? MtdStatus { get; set; }
        [Column("MTD_CREATE_BY")]
        public int? MtdCreateBy { get; set; }
        [Column("MTD_CREATE_DATE", TypeName = "datetime")]
        public DateTime? MtdCreateDate { get; set; }
        [Column("MTD_UPDATE_BY")]
        public int? MtdUpdateBy { get; set; }
        [Column("MTD_UPDATE_DATE", TypeName = "datetime")]
        public DateTime? MtdUpdateDate { get; set; }
    }
}