// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("SCHEDULE_COURSE_COST")]
    public partial class ScheduleCourseCost
    {
        [Key]
        [Column("SC_ID")]
        public int ScId { get; set; }
        [Key]
        [Column("SCD_ID")]
        public int ScdId { get; set; }
        [Key]
        [Column("MEXP_ID")]
        public int MexpId { get; set; }
        [Column("cost")]
        public double? Cost { get; set; }
    }
}