// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("SCHEDULE_COURSE")]
    public partial class ScheduleCourse
    {
        [Key]
        [Column("SC_ID")]
        public int ScId { get; set; }
        [Column("sc_name")]
        [StringLength(300)]
        public string ScName { get; set; }
        [Column("sc_start_date", TypeName = "date")]
        public DateTime? ScStartDate { get; set; }
        [Column("sc_stop_date", TypeName = "date")]
        public DateTime? ScStopDate { get; set; }
        [Column("sc_total_course")]
        public int? ScTotalCourse { get; set; }
        [Column("sc_total_emp")]
        public int? ScTotalEmp { get; set; }
        [Column("sc_status")]
        public byte? ScStatus { get; set; }
        [Column("sc_create_date", TypeName = "datetime")]
        public DateTime? ScCreateDate { get; set; }
        [Column("sc_create_by")]
        [StringLength(20)]
        public string ScCreateBy { get; set; }
        [Column("sc_update_date", TypeName = "datetime")]
        public DateTime? ScUpdateDate { get; set; }
        [Column("sc_update_by")]
        [StringLength(20)]
        public string ScUpdateBy { get; set; }
    }
}