// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace StandardCanMobileAPI.Models
{
    [Table("USERS")]
    public partial class Users
    {
        public Users()
        {
            MasHardwareMhwCreateByNavigation = new HashSet<MasHardware>();
            MasHardwareMhwUpdateByNavigation = new HashSet<MasHardware>();
        }

        [Key]
        [Column("USR_ID")]
        public int UsrId { get; set; }
        [Required]
        [Column("USR_CODE")]
        [StringLength(10)]
        public string UsrCode { get; set; }
        [Column("USR_TITLE")]
        [StringLength(50)]
        public string UsrTitle { get; set; }
        [Required]
        [Column("USR_FNAME")]
        [StringLength(50)]
        public string UsrFname { get; set; }
        [Column("USR_LNAME")]
        [StringLength(50)]
        public string UsrLname { get; set; }

        [InverseProperty(nameof(MasHardware.MhwCreateByNavigation))]
        public virtual ICollection<MasHardware> MasHardwareMhwCreateByNavigation { get; set; }
        [InverseProperty(nameof(MasHardware.MhwUpdateByNavigation))]
        public virtual ICollection<MasHardware> MasHardwareMhwUpdateByNavigation { get; set; }
    }
}